version: "3.9"
services:
  postgres:
    image: postgres:14
    container_name: dastyare_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dastyare_subscription
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
